export const FETCH_COIN_PRICE_ERROR = 'FETCH_COIN_PRICE_ERROR';
export const FETCH_COIN_PRICE_PENDING = 'FETCH_COIN_PRICE_PENDING';
export const FETCH_COIN_PRICE_SUCCESS = 'FETCH_COIN_PRICE_SUCCESS';
export const SET_TEST = 'SET_TEST';
export const SET_ELSE = 'SET_ELSE';
